### ISSUE TITLE
Release training code and model?

### ISSUE THREAD

**Issue by coolKeen** [hific/hific.github.io#2]
Hi, thanks for your nice work! Do you have any plan for releasing training code and pretrained models?
Thanks in advance!

**Comment by gtoderici** [comment]
The training code is already released [here](https://github.com/tensorflow/compression/tree/master/models/hific) with a colab that runs our model [here](https://colab.research.google.com/github/tensorflow/compression/blob/master/models/hific/colab.ipynb). The main issue is that we haven't found an open dataset yet we could plug in to get the same results.

We haven't updated the landing page yet due to it not being "100% tested" (see my comment above about training).

**Comment by fab-jul** [comment]
Everything is now updated, please see: https://hific.github.io
